<?php

namespace Tests\Feature;

use Database\Seeders\UserSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class UserControllerTest extends TestCase
{

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete("delete from users");
    }

    public function testLoginPage(){
        $this->get('/login')->assertSeeText('Login');
    } // Test Login Page 

    public function testLoginSuccess(){
        $this->seed(UserSeeder::class);
        $this->post('/login', [
            'email' => 'eko@localhost',
            'password' => 'rahasia',
        ])->assertRedirect("/")
        ->assertSessionHas("email", "eko@localhost");
    }

    public function testLoginValidationError(){
        $this->post("/login", [])
            ->assertSeeText("Email Or Password Is Required");
    }

    public function testLoginFailed(){
        $this->post('/login', [
            'email' => 'eko@localhost',
            'password' => 'salah',
        ])->assertSeeText('Email Or Pasword Is Wrong');
    }
}
